package com.mushanwb.github.wxshop.generate;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;

import java.util.Date;

@SuppressFBWarnings(value = {"EI_EXPOSE_REP", "EI_EXPOSE_REP2"})
public class ShoppingCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.id
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.user_id
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.goods_id
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.number
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.status
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.created_at
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.updated_at
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.id
     *
     * @return the value of shopping_cart.id
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.id
     *
     * @param id the value for shopping_cart.id
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.user_id
     *
     * @return the value of shopping_cart.user_id
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.user_id
     *
     * @param userId the value for shopping_cart.user_id
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.goods_id
     *
     * @return the value of shopping_cart.goods_id
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.goods_id
     *
     * @param goodsId the value for shopping_cart.goods_id
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.number
     *
     * @return the value of shopping_cart.number
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.number
     *
     * @param number the value for shopping_cart.number
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.status
     *
     * @return the value of shopping_cart.status
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.status
     *
     * @param status the value for shopping_cart.status
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.created_at
     *
     * @return the value of shopping_cart.created_at
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.created_at
     *
     * @param createdAt the value for shopping_cart.created_at
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.updated_at
     *
     * @return the value of shopping_cart.updated_at
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.updated_at
     *
     * @param updatedAt the value for shopping_cart.updated_at
     *
     * @mbg.generated Fri Nov 13 14:56:58 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}